(function(g){var window=this;var uoa=function(a){if(!a.Ia||!a.Ia.annotations)return null;a=g.p(a.Ia.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer;return null},O1=function(a){a.u||(a.u=new g.vn,g.B(a,a.u));
return a.u},P1=function(a){a.R("cardstatechange",g.qL(a)&&g.rL(a)?1:0)},voa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Xj&&a.dataset){if(g.gc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.bd("pollChoiceIndex"))},woa=function(a){return Math.pow(a,3)},xoa=function(a){return 3*a*a-2*a*a*a},Q1=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.eB(c),eventType:4};var d={tj:void 0,Hh:a};"UNDEFINED_CSN"==a?g.pB("visualElementShown",c,d):g.zr("visualElementShown",c,g.Er,d)})},R1=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.eB(c),eventType:d?16:8};d={tj:void 0,Hh:a,jD:d};"UNDEFINED_CSN"==a?g.pB("visualElementHidden",c,d):g.zr("visualElementHidden",c,g.Er,d)})},U1=function(a){a=g.Na(a);
delete S1[a];g.Wb(S1)&&T1&&T1.stop()},V1=function(){T1||(T1=new g.J(function(){yoa()},20));
var a=T1;a.isActive()||a.start()},yoa=function(){var a=(0,g.F)();
g.Ib(S1,function(b){W1(b,a)});
g.Wb(S1)||V1()},X1=function(a,b,c,d){g.kn.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.D=null},W1=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.D);a.D=b;Y1(a,a.progress);1==a.progress?(a.o=0,U1(a),a.cd(),a.w()):1==a.o&&a.Ur()},Y1=function(a,b){g.Ka(a.G)&&(b=a.G(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.J[c]-a.A[c])*b+a.A[c]},Z1=function(a,b){g.fe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},$1=function(a,b,c,d,e){X1.call(this,b,c,d,e);
this.element=a},a2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$1.call(this,a,b,c,d,e)},b2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},zoa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.or(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},c2=function(a){return a.baseUrl||null},Aoa=function(a,b,c){function d(na){var Ia=na.hovercardButton;
if(!Ia)return null;Ia=Ia.subscribeButtonRenderer;if(!Ia)return null;var Tb=f(Ia.unsubscribedButtonText),Xc=f(Ia.subscribedButtonText);if(Ia.subscribed){var Mf=f(Ia.subscriberCountWithUnsubscribeText);var Xe=f(Ia.subscriberCountText)}else Mf=f(Ia.subscriberCountText),Xe=f(Ia.subscriberCountWithSubscribeText);var Zd=null;return na.signinEndpoint&&(Zd=g.Qb(na,"signinEndpoint","webNavigationEndpointData","url"),!Zd)?null:Tb&&(Xc||Zd)?{subscribed:Ia.subscribed,subscribeText:Tb,subscribeCount:Mf,unsubscribeText:Xc,
unsubscribeCount:Xe,enabled:Ia.enabled,signinUrl:Zd,classic:na.useClassicSubscribeButton}:null}
function e(na){if(na){var Ia=[],Tb=na.videoId;Tb&&Ia.push("v="+Tb);(Tb=na.playlistId)&&Ia.push("list="+Tb);(na=na.startTimeSeconds)&&Ia.push("t="+na);return"/watch?"+Ia.join("&")}}
function f(na){if(!na)return null;var Ia=na.simpleText;return Ia?Ia:na.runs?(0,g.H)(na.runs,function(Tb){return Tb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,z=null,C=!1,D=null,G=null,K=null,E=null,N=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Qb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;q="new";(C=!!b.isSubscribe)?D=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((K=g.Qb(l,"urlEndpoint","url"))&&(m=K),n=!0,q="new",K=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=g.Qb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");var ka=b.endpoint?b.endpoint.clickTrackingParams:null;return{id:"element-"+c,type:k,title:f(b.title),metadata:b.metadata?f(b.metadata):"",callToAction:f(b.callToAction),gv:b.image,iconUrl:K,
left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:G,isSubscribe:C,targetUrl:m,LE:n,Gb:{itct:ka},HN:q,kj:a?a:null,PE:b.isPlaceholder,impressionUrls:(0,g.H)(b.impressionUrls||[],c2),BE:(0,g.H)(b.hovercardShowUrls||[],c2),clickUrls:(0,g.H)(l.loggingUrls||[],c2),visualElement:g.dB(b.trackingParams),productPrice:E,
additionalFeesText:N}},d2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.H)(a.impressionUrls||[],c2);a.trackingParams&&(c.visualElement=g.dB(a.trackingParams));var d=(0,g.H)(a.elements||[],function(e,f){return Aoa(b,e,f)});
c.elements=(0,g.Rd)(d,function(e){return!!e});
return c},e2=function(a){g.VQ.call(this,a);
this.w=this.u=null;this.o={};this.D={};this.C=this.A=null;this.H=[];a=a.P();this.J=g.qy(a)||g.sy(a);this.K=!0;this.G=0;this.B=new g.R(this);g.B(this,this.B);this.B.M(this.player,g.tE("creatorendscreen"),this.yF);this.B.M(this.player,"crx_creatorendscreen",this.zF);this.B.M(this.player,"resize",this.kx);this.B.M(window,"focus",this.DM);this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ce(this,function(){g.Qd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},f2=function(a){return a.player.getVideoData().dc?"current":a.J?"new":"current"},g2=function(a){return"creator-endscreen-editor"===a.player.P().playerStyle},h2=function(a,b,c){c=void 0===c?!0:c;
g.oS(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.D={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&Boa(a);c=[];d=new g.qE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.P().o||(a.A=new g.T({F:"div",I:"ytp-ce-shadow"}),g.BL(a.player,a.A.element,4),a.C=new g.gN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Coa(a,e);a.o[e.id]=f;a.D[e.id]=e;g.BL(a.player,f.element,4);var k=new g.qE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Doa(a,f,e)}g.xL(a.player,c);
a.kx()}},Boa=function(a){var b=g.yB(),c=g.zB();
c&&b&&a.u.visualElement&&g.qB(c,b,[a.u.visualElement],void 0)},Coa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",Y:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.kj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",O:i2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",O:{href:j2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.on(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={F:"div",Y:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.kj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",O:i2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",O:{href:j2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.on(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={F:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.kj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],O:{href:j2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.on(b.title||"")},W:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{F:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",O:i2(b)}]};c=new g.T(c);var d=g.xd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.P().o){var e=null;var f=b.Gb.itct}else e="endscreen",f=null;e=new g.AR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={F:"div",Y:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.kj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",O:{dir:g.on(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-website-metadata",W:b.metadata},{F:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],O:{href:j2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",O:i2(b)},{F:"div",I:"ytp-ce-expanding-icon",O:k2(b.iconUrl)}]};c=new g.T(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={F:"div",I:"ytp-ce-merchandise-price-container",
L:[{F:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.L.push({F:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={F:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.kj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",
I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",O:{dir:g.on(b.title||"")},W:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{F:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:j2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",O:i2(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.T(c)}b.PE&&g.L(c.element,"ytp-ce-placeholder");return c},i2=function(a){if(a.gv)var b=a.gv.thumbnails;
return k2(b?b[b.length-1].url:null)},k2=function(a){return a?{style:"background-image: url("+a+")"}:{}},Doa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ha("mouseenter",(0,g.x)(a.Vq,a,b,c));b.ha("mouseleave",(0,g.x)(a.ds,a,b,c));a.player.P().o||b.ha("click",(0,g.x)(function(l){g.L(l.element,"ytp-ce-element-hover")},a,b));
b.ha("click",(0,g.x)(a.Vy,a,c));b.ha("keypress",(0,g.x)(a.Vy,a,c));b.ha("focus",(0,g.x)(function(l,m){this.Vq(l,m)},a,b,c));
b.ha("blur",(0,g.x)(function(l,m){this.ds(l,m)},a,b,c));
b.ha("touchstart",(0,g.x)(a.Vq,a,b,c));var f=g.zd("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.hn(b.element,"ytp-ce-element-hover");g.hn(b.element,"ytp-ce-force-expand")});
b.ha("keydown",(0,g.x)(function(l,m){this.K=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.L(l.element,"ytp-ce-force-expand"),l2(this,m.id,!0)):(g.hn(l.element,"ytp-ce-force-expand"),g.hn(l.element,"ytp-ce-element-hover"),l2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ha("blur",g.Oa(function(){"none"!=m.style.display&&a.K&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.zd("ytp-sb-subscribe",b.element));c(g.zd("ytp-sb-unsubscribe",b.element));b.ha("focus",d);b.ha("blur",e)},j2=function(a,b){var c=a.player.P();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Qy(c)+b}else return"";return b},l2=function(a,b,c){a.A&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.M(a.o[d].element,"ytp-ce-element-shadow-show",c)},m2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||g2(a))c&&c();else{b=Eoa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Np(b[a],d)}},n2=function(a,b,c){m2(a,b.clickUrls,c);
(a=g.zB())&&b.LE&&g.sB(a,b.visualElement)},Eoa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Foa(b[e],c));return d},Foa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},o2=function(a){return g.Ha(a)&&a.length?a[0]:a},p2=function(a){return"string"===typeof a?a:""},q2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Hoa=function(a){var b=Goa;
if(null==a)return null;if(g.Ja(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Ioa=function(a){this.externalId=a},r2=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},s2=function(a){if(!a)return null;
var b=g.yc(p2(a.value));b=g.wc(b);if(!b)return null;var c=q2(a.target,Joa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new r2(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},t2=function(a){return a.value?a.value:null},u2=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Goa=function(a){if(!a)return null;
var b=q2(a.type,Koa),c=q2(a.trigger,Loa),d=o2(a.url);d=s2(d?d:null);a=o2(a.subscribeData);var e=a?a:null;e?(a=p2(e.external_user_id),e=p2(e.subscription_token),a=a&&e?new Ioa(a):null):a=null;return b?new u2(b,c,d,a):null},v2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},w2=function(a){return(a=Moa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Moa=function(a,b){return g.Va(a.o,b,void 0)},x2=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Noa=function(a,b){this.merchant=a;
this.price=b},Ooa=function(a){this.o=a},Poa=function(a,b,c){b&&(c?y2(a,(0,g.H)(b,g.Oa(function(d,e){return g.Tm(e,d)},c))):y2(a,b))},y2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Np(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Qoa=function(a,b,c,d,e,f,k){this.o=a;
this.A=b;this.Ya=c;this.videoData=d;this.logger=e;this.ca=f;this.u=k},z2=function(a,b){this.o=a;
this.A=b},Soa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Roa(b,k))},a);
var d={F:"ul",O:{role:"radiogroup"},L:c},e={};b.Lh&&(e["aria-label"]=g.QN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[A2("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.Lh&&(f.push("iv-card-unavailable"),d.push({F:"div",Y:["iv-card-sign-in"],L:[{F:"h2",W:"Want to vote?"},{F:"a",Y:["iv-card-sign-in-button","iv-button"],O:{href:t2(b.Lh)},L:[{F:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.T({F:"div",
Y:f,L:d});d=f.element;B2(b,d);zoa(a.o.o,d,g.Oa(a.w,b),a);(0,g.y)(g.yd("iv-card-poll-choice-input",d),function(k){this.o.o.ha(k,"focus",g.Oa(this.u,!0));this.o.o.ha(k,"blur",g.Oa(this.u,!1))},a);
b.Lh&&(d=g.zd("iv-card-sign-in-button",d),a.A(d,b.Lh,b.id,b.Gb,b.uc.click,5));return f},F2=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.aO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.OE&&b.Gu?{F:"span",Y:d,O:e,W:b.Gu}:"";c={F:"div",Y:["iv-card",c],L:[{F:"a",I:"iv-click-target",O:{href:t2(b.url)},L:[C2(b.Oh,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",W:b.title},D2(a,b)]}]}]};c=new g.T(c);E2(a,g.yd("iv-click-target",c.element),b,b.url);return c},G2=function(a){return a.customMessage?
A2("div","iv-card-message",a.customMessage):""},C2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",O:{style:c},L:d}},D2=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(A2("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},Roa=function(a,b){return{F:"li",
I:x2(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",O:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},A2("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},A2=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ha(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.on(c);return{F:a,O:b,W:c}},H2=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Gl&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Gl+");");c.dir=g.on(a.customMessage);var d=[{F:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",Y:b,O:c,L:d}},B2=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.zd(x2(a,e.index),b);e=e.count/c;null==a.je&&(e=0);g.M(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.je==d);f.getElementsByTagName("input")[0].checked=a.je==d;var k=Math.floor(100*e).toFixed(0),l=g.zd("iv-card-poll-choice-percent",f);g.Vd(l,g.QN("$PERCENT%",{PERCENT:k}));f=g.zd("iv-card-poll-result-bar",f);g.kh(f,"transform","scaleX("+e.toFixed(2)+")")}g.M(b,"iv-card-poll-voted",null!=a.je);g.M(b,"iv-card-poll-expanded",
null!=a.je&&1<a.choices.length)},E2=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.A(e,d,c.id,c.Gb,c.uc.click,5)},a)},I2=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Toa=function(a,b){return b?b:I2(a)?"current":"new"},J2=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.Bt=!1},Uoa=function(a,b,c,d,e){var f=t2(b);
if(f){var k=Toa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ca.pauseVideo();var m=this.context.videoData.dc||!1,n=g.$o(f||"");m&&n&&(n.v||n.list)?g.JU(this.context.ca.app,n.v,c,n.list,!1,void 0):g.WN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);y2(a.context.logger,d,l,e);I2(f)||(a=g.zB(),d=c.itct,a&&d&&g.sB(a,g.dB(d)))}},K2=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},L2=function(a,b,c){return{xw:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
KA:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
lo:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},O2=function(a,b,c){J2.call(this,b,c);
var d=this;this.A=a;this.da=this.ya=this.C=this.xa=!1;this.aa=null;this.X=new g.J(g.Ea,c.Ya.Ma?4E3:3E3);g.B(this,this.X);this.ga=new g.J(g.Ea);g.B(this,this.ga);this.H=new z2(c,(0,g.x)(this.Vi,this),(0,g.x)(this.Nm,this));this.S=new g.T({F:"div",I:"iv-drawer",O:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",O:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",Y:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.B(this,this.S);this.D=this.S.element;this.ia=new g.gN(this.S,330);g.B(this,this.ia);this.ra=g.zd("iv-drawer-header-text",this.D);this.B=g.zd("iv-drawer-content",this.D);this.w=[];this.oa=this.N=this.G=this.ba=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&M2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.C)&&N2(d)});
this.U=this.J=this.ea=null;this.K=0},Voa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){M2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){N2(a)});
var c=b.data.headerText;g.Vd(a.ra,c);a.N&&a.N.setAttribute("title",c);a.ea=g.dB(b.data.trackingParams);a.U=g.dB(b.data.closeTrackingParams);a.J=g.dB(b.data.iconTrackingParams)},Woa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"simple",teaserText:g.RA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:P2(a,c,b,d),sponsored:!1,uc:L2(d,e,d.command),Jd:d.trackingParams?g.dB(d.trackingParams):null,Ed:e.trackingParams?
g.dB(e.trackingParams):null,Uc:f&&f.trackingParams?g.dB(f.trackingParams):null,imageUrl:Q2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.RA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Gl:null,title:d.title?g.RA(d.title):"",customMessage:d.callToAction?g.RA(d.callToAction):"",url:d.command.urlEndpoint.url?s2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};R2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"collaborator",teaserText:g.RA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:P2(a,c,b,d),sponsored:!1,uc:L2(d,e,d.endpoint),Jd:d.trackingParams?g.dB(d.trackingParams):null,Ed:e.trackingParams?g.dB(e.trackingParams):null,Uc:f&&f.trackingParams?
g.dB(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.RA(d.customText):null,Iz:Q2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.RA(d.channelName):"",metaInfo:[d.subscriberCountText?g.RA(d.subscriberCountText):""],url:s2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};R2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"playlist",teaserText:g.RA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:P2(a,c,b,d),sponsored:!1,uc:L2(d,e,d.action),Jd:d.trackingParams?g.dB(d.trackingParams):null,Ed:e.trackingParams?g.dB(e.trackingParams):null,Uc:f&&f.trackingParams?g.dB(f.trackingParams):
null,Oh:Q2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.RA(d.customMessage):null,playlistVideoCount:g.RA(d.playlistVideoCount),title:d.playlistTitle?g.RA(d.playlistTitle):"",metaInfo:[d.channelName?g.RA(d.channelName):"",d.videoCountText?g.RA(d.videoCountText):""],url:s2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:K2(d.action)})};R2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"video",teaserText:g.RA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Gb:P2(a,c,b,d),sponsored:!1,uc:L2(d,e,d.action),Jd:d.trackingParams?g.dB(d.trackingParams):null,Ed:e.trackingParams?g.dB(e.trackingParams):null,Uc:f&&f.trackingParams?g.dB(f.trackingParams):null,Oh:Q2(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.RA(d.lengthString):null,customMessage:d.customMessage?g.RA(d.customMessage):null,title:d.videoTitle?g.RA(d.videoTitle):"",metaInfo:[d.channelName?g.RA(d.channelName):"",d.viewCountText?g.RA(d.viewCountText):""],isLiveNow:!!d.badge,url:s2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:K2(d.action)})};R2(a,c)}a.K++},Q2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},P2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},T2=function(a,b){var c=Xoa(a,b);
c&&(c==a.u&&(a.u=null),a.A.removeCueRange(c.card.id),g.Qd(c.ip),g.bb(a.w,c),a.Il(),S2(a))},M2=function(a,b,c){if(!a.C){a.ia.show();
a.ba=new g.J(function(){g.L(a.context.ca.getRootNode(),"ytp-iv-drawer-open")},0);
a.ba.start();a.aa=g.fr(a.B,"mousewheel",(0,g.x)(a.VF,a));a.C=!0;var d=g.zB();d&&a.ea&&a.U&&Q1(d,[a.ea,a.U]);var e={TRIGGER_TYPE:b};(0,g.y)(a.w,function(f){f.Xw||(f.Xw=!0,Poa(a.context.logger,f.card.uc.xw,e));d&&Q1(d,[f.card.Jd])});
P1(a.A);c&&(a.G=new g.J(function(){a.sa=a.N;a.oa.focus()},330),a.G.start())}},N2=function(a){a.C&&(a.ia.hide(),g.gr(a.aa),a.aa=null,g.hn(a.context.ca.getRootNode(),"ytp-iv-drawer-open"),a.C=!1,P1(a.A),a.G&&a.G.stop(),a.G=new g.J(function(){a.sa&&(a.sa.focus(),a.sa=null)},330),a.G.start())},Yoa=function(a){var b=g.zd("iv-drawer-close-button",a.D);
a.context.o.ha(b,"click",a.SC,a);a.context.o.ha(a.B,"touchend",function(){a.X.start()});
a.context.o.ha(a.B,"scroll",a.gD,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.fn(a.A.getRootNode(),"ytp-autohide")});
a.V.push(g.Ao("iv-button-shown",a.aF,a));a.V.push(g.Ao("iv-button-hidden",a.ZE,a));a.V.push(g.Ao("iv-teaser-shown",a.dF,a));a.V.push(g.Ao("iv-teaser-hidden",a.cF,a));a.V.push(g.Ao("iv-teaser-clicked",a.bF,a))},R2=function(a,b){a.xa||(g.gn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.BL(a.A,a.D,5),Yoa(a),a.N=g.zd("ytp-cards-button",a.A.getRootNode()),a.oa=g.zd("iv-drawer-close-button",a.D),a.xa=!0);T2(a,b.id);var c=Zoa(a,b);if(c){var d={card:b,ip:c.element,Xw:!1},e=$oa(a,d);g.ib(a.w,e,0,d);c.o(a.B,e);a.Il();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Oa(a.rN,d)):(c=1E3*a.context.ca.getCurrentTime(),5E3>c&&c>b.startMs&&a.pA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Oa(a.pA,d)),S2(a))}},Zoa=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=H2(b);d={F:"div",Y:["iv-card"],L:[{F:"a",I:"iv-click-target",O:{href:t2(b.url)},L:[C2(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[A2("h2",void 0,b.title),e]}]}]};d=new g.T(d);E2(c,g.yd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",Y:["iv-card","iv-card-channel"],L:[{F:"a",Y:["iv-click-target"],O:{href:t2(b.url),"data-ytid":b.channelId},L:[C2(b.Iz),{F:"div",I:"iv-card-content",
L:[G2(b),{F:"h2",I:"iv-card-primary-link",W:b.title},D2(c,b)]}]}]},d=new g.T(d),E2(c,g.yd("iv-click-target",d.element),b,b.url),d;case "episode":return F2(a.H,b,"iv-card-episode");case "movie":return F2(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",Y:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",O:{href:t2(b.url)},L:[C2(b.Oh,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[G2(b),
A2("h2","iv-card-primary-link",b.title),D2(c,b)]}]}]},d=new g.T(d),E2(c,g.yd("iv-click-target",d.element),b,b.url),d;case "poll":return Soa(a.H,b);case "productListing":c=a.H;var f=!g.Za(b.offers);d=["iv-card"];e="";var k=H2(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={F:"div",L:k});d={F:"div",Y:d,O:{tabindex:"0"},L:[{F:"a",Y:["iv-card-image",
"iv-click-target"],O:{style:"background-image: url("+b.imageUrl+");",href:t2(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",W:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",O:{href:t2(b.url)},L:[A2("h2",e,b.title),k]}]}]};d=new g.T(d);e=g.Ld("span");
g.Vd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(e,"adInfo");E2(c,g.yd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={F:"div",Y:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",O:{href:t2(b.url)},L:[C2(b.Oh,b.videoDuration?{F:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[G2(b),A2("h2","iv-card-primary-link",b.title),D2(c,b),d]}]}]},d=new g.T(d),E2(c,g.yd("iv-click-target",d.element),b,b.url),d}return null},$oa=function(a,b){if(0==a.w.length)return 0;
var c=g.Wa(a.w,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},apa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.mi)(a.w,function(b){return"productListing"==b.card.type})},S2=function(a){g.M(a.A.getRootNode(),"ytp-cards-shopping-active",apa(a))},U2=function(a,b){if(a.S.Ha()){var c=new X1([0,
a.B.scrollTop],[0,b.ip.offsetTop],600,xoa);a.context.A.ha(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.ha(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.zu(a.S,!0),a.B.scrollTop=b.ip.offsetTop,g.zu(a.S,!1)},V2=function(a){return a.u&&a.u.card?a.u.card:a.w[0]&&a.w[0].card?a.w[0].card:null},Xoa=function(a,b){return g.Va(a.w,function(c){return c.card.id==b})},W2=function(a,b,c){J2.call(this,a,b);
this.annotation=c;this.isActive=!1},bpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},X2=function(a,b,c){W2.call(this,a,b,c);
this.A=null;this.G=!1;this.w=null;this.B=!1;this.u=this.D=this.C=null},Y2=function(a,b,c){W2.call(this,a,b,c);
this.J=this.C=this.K=!1;this.G=5E3;this.B=null;this.H=g.Kd("DIV","iv-promo-contents");this.A=this.w=this.u=null;this.D=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Fh(this.w,!1);g.Fh(this.A,!0)},700,this);
g.B(this,this.D)},cpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=w2(a.annotation),f=b.image_url;if(f){var k=g.Kd("DIV",["iv-promo-img","iv-click-target"]);f=g.Kd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Kd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Kd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Vi(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Kd("A","iv-promo-txt"),g.Qc(f,t2(e)),a.u=f):a.u=g.Kd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_1));var m=g.Kd("P",null,g.Kd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.U(a.context.Ya.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Kd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Kd("BUTTON",["iv-button","iv-promo-button"],g.Kd("SPAN","iv-button-content",f));var q=g.Kd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Vi(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.u,"iv-click-target");e&&a.Vi(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Kd("P",null,g.Kd("SPAN",null,b.text_line_1)),
m=g.Kd("P",null,g.Kd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Kd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.L(a.u,"iv-click-target"),e&&a.Vi(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Kd("DIV","iv-promo-actions");a.A=g.Kd("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="Expand";a.context.o.ha(a.A,"click",g.Oa(a.Zp,5E3),a);c.appendChild(a.A);g.Fh(a.A,!1);
a.context.o.ha(a.o,"mouseover",a.dE,a);a.context.o.ha(a.o,"mouseout",a.cE,a);a.context.o.ha(a.o,"touchend",g.Oa(a.Zp,5E3),a);a.w=g.Kd("BUTTON",["iv-promo-close","ytp-button"]);a.w.title="Close";a.context.o.ha(a.w,"click","cta"==a.annotation.style&&b.text_line_3?a.WD:a.VD,a);c.appendChild(a.w);g.gn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},Z2=function(a){a.C||a.J||a.B||(g.L(a.o,"iv-promo-collapsed"),a.C=!0,a.D.start())},$2=function(a){a.D.stop();
a.C&&(g.jn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Fh(a.A,!1),g.Fh(a.w,!0))},b3=function(a,b){a.B||(a.B=g.qf(function(){a3(this);
Z2(this)},b,a))},a3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},c3=function(a){g.VQ.call(this,a);
this.J=!1;this.H=0;this.D={};this.S=new Ooa(a);this.B=new g.R(this);g.B(this,this.B);this.C=this.A=null;this.B.M(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.M(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.M(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.M(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.M(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.bL,this);this.subscribe("resize",this.In,this);this.player.P().D.subscribe("vast_info_card_add",this.wz,this);this.N=new g.R(this);g.B(this,this.N);this.U=g.Kd("DIV","video-custom-annotations");this.u=new g.T({F:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.BL(this.player,this.u.element,4);this.u.hide();this.w=new g.T({F:"div",Y:["ytp-iv-video-content"]});g.B(this,this.w);g.Nd(this.w.element,g.Kd("DIV","video-annotations",
this.U));this.G=this.o=null;this.K=[];dpa(this)&&this.load();var b=g.Ld("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ce(this,function(){g.Qd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},d3=function(){var a=g.Kd("DIV",["annotation",
"annotation-type-custom"]);g.Fh(a,!1);return a},e3=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},dpa=function(a){var b=a.player.P();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.qB||null!==b.D.get(a.videoId)},f3=function(a,b,c){a.J=!0;
a.C=g.tp(b,c)},g3=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(g3(a,e))}return c},h3=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},epa=function(a){var b=a.player.getVideoData();
if(b.Id){var c=a.player.P().D.get(b.videoId);if(c){var d={format:"XML",Gd:{},method:"POST",withCredentials:!0};d.cd=(0,g.x)(function(e,f,k){h3(this,e,f)||(e=g.np(k)&&k.responseXML?k.responseXML:null)&&i3(this,e)},a,a.H,b.videoId);
g.Po()&&(d.cd=j3(a,d.cd));d.vb={ic_only:"1"};k3(d,c);a.J=!0;g.tp(b.Id,d)}}},k3=function(a,b){a.method="POST";
a.vb=a.vb||{};b.Ml&&(a.vb.ic_coll=b.Ml);b.Nl&&(a.vb.ic_xml=b.Nl);b.Zk&&(a.vb.ic_track=b.Zk)},m3=function(a){var b=new g.T({F:"div"});
g.Fh(b.element,!1);var c=new O2(a.player,b.element,l3(a));g.B(c,b);b.o(a.u.element);c.Nk();return c},l3=function(a){if(!a.G){var b=new b2(a);
g.B(a,b);var c=new g.p0(a);g.B(a,c);a.G=new Qoa(b,c,a.player.P(),a.player.getVideoData(),a.S,a.player,a.Wb)}return a.G},i3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.zB();if(e){var f=g.yB();f&&g.qB(e,f,[g.dB(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=g3(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=q2(k.type,fpa),t=q2(k.style,gpa),u=p2(k.data),z=0!=u.length?JSON.parse(u):{},C=Hoa(k.action);f=n&&q?new v2(n,q,t,C,z):null}else f=null}catch(N){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=d3(),G=null;switch(m.type){case "branding":if(k.player.P().La)break;k.u.element.appendChild(D);G=new X2(D,l3(k),m);break;case "promotion":g.BL(k.player,D,4),G=new Y2(D,l3(k),m)}G&&G.Nk();if(k=G)g.B(a,k),a.D[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=m3(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={xw:k.impression,click:k.click,close:k.close,KA:k.teaser_impression,lo:k.teaser_click},m=f.data.tracking_params||
{},D=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,Iz:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:s2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};R2(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):
null,Oh:f.data.image_url,Gu:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,OE:!!f.data.is_paygated,aO:!!f.data.user_has_entitlement,url:s2({target:f.data.target||"new",value:f.data.url})};R2(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):null,Oh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:s2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};R2(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):null,title:f.data.title,choices:f.data.choices,je:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Lh:f.data.signin_url?s2({target:"current",value:f.data.signin_url}):null,lO:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};R2(c,f);break;case "productListing":f.data.signin_url&&(D=s2({target:"current",
value:f.data.signin_url}));G=[];for(var K=f.data.offers||[],E=0;E<K.length;E++)G.push(new Noa(g.Yc(K[E].merchant),g.Yc(K[E].price)));f={lS:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Gl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:s2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Lh:D,xS:f.data.signin_title?f.data.signin_title:null,wS:f.data.signin_message?f.data.signin_message:null,offers:G};R2(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):null,Uc:m.icon?g.dB(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Gl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:s2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};R2(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Gb:f.data.session_data||{},sponsored:f.data.sponsored||!1,uc:k,Jd:m.card?g.dB(m.card):null,Ed:m.teaser?g.dB(m.teaser):
null,Uc:m.icon?g.dB(m.icon):null,Oh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:s2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},R2(c,f)}}else Voa(a.o,f);c=!0}}}c&&(P1(a.player),a.In())},hpa=function(a,b){var c=!1;
a.o||(a.o=m3(a),g.B(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Woa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.RA(b.headerText):"",g.Vd(c.ra,d),c.N&&c.N.setAttribute("title",d),c.ea=b.trackingParams?g.dB(b.trackingParams):null,c.U=b.closeButton.infoCardIconRenderer.trackingParams?g.dB(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.dB(b.icon.infoCardIconRenderer.trackingParams):null,P1(a.player),a.In())},
ipa=function(a,b,c,d,e){if(!a.player.P().La){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new u2("openUrl","click",new r2("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.RA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.RA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.RA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.RA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.RA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.RA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new v2(c,"branding","branding",f,d);d=d3();a.u.element.appendChild(d);f=new X2(d,l3(a),f);f.Nk();g.B(f,f);a.D[c]=f}},j3=function(a,b){return(0,g.x)(function(){if(!this.ka()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Oa.apply(window,c);this.K.push(g.No(b))}},a)},S1={},T1=null;g.Qa(X1,g.kn);g.h=X1.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(1==this.o)return!1;U1(this);this.startTime=a=(0,g.F)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.B();this.Zd("play");-1==this.o&&this.Zd("resume");this.o=1;var b=g.Na(this);b in S1||(S1[b]=this);V1();W1(this,a);return!0};
g.h.stop=function(a){U1(this);this.o=0;a&&(this.progress=1);Y1(this,this.progress);this.Zd("stop");this.w()};
g.h.pause=function(){1==this.o&&(U1(this),this.o=-1,this.Zd("pause"))};
g.h.Z=function(){0==this.o||this.stop(!1);this.Zd("destroy");X1.yb.Z.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ur=function(){this.Zd("animate")};
g.h.Zd=function(a){this.dispatchEvent(new Z1(a,this))};
g.Qa(Z1,g.fe);g.Qa($1,X1);$1.prototype.C=g.Ea;$1.prototype.Ur=function(){this.C();$1.yb.Ur.call(this)};
$1.prototype.w=function(){this.C();$1.yb.w.call(this)};
$1.prototype.B=function(){this.C();$1.yb.B.call(this)};
g.Qa(a2,$1);a2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(b2,g.A);b2.prototype.ha=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.fr(a,b,c);this.o.push(a);return a};
b2.prototype.Hq=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.pr(a,b,c);this.o.push(a);return a};
b2.prototype.Ua=function(a){g.gr(a);g.bb(this.o,a)};
b2.prototype.Z=function(){g.gr(this.o);this.o.length=0;g.A.prototype.Z.call(this)};g.r(e2,g.VQ);g.h=e2.prototype;g.h.load=function(){g.VQ.prototype.load.call(this);if(!g2(this)){var a=g.cD(this.player.getVideoData());if(a)a=d2(a,f2(this)),h2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.w&&this.w.abort();a={method:"POST",cd:(0,g.x)(this.OJ,this,a),Gd:{v:a},withCredentials:!0};this.J&&(a.Gd.ptype="embedded");var c=this.player.getVideoData().Zl;c&&(a.vb={ad_tracking:c});if(b=g.bD(b))if(b=g.yc(b),b=g.wc(b))this.w=g.tp(b,a)}}};
g.h.unload=function(){h2(this,null);this.w&&(this.w.abort(),this.w=null);g.VQ.prototype.unload.call(this)};
g.h.Ac=function(a,b){if(!g2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=d2(b,"new");h2(this,c);return!0}return null};
g.h.getOptions=function(){return g2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.OJ=function(a,b){var c=this.w=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=d2(c,f2(this)))}h2(this,c)};
g.h.kx=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<n3.length;f++){var k=Math.abs(b.width-n3[f]);if(-1==e||d>=k)e=f,d=k}d=o3[e];this.A&&g.kh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Dh(e.element,Math.round(k.width*a.width),f);g.sh(e.element,m,n);g.jn(e.element,jpa);m=k.left+k.width/2;k=k.top+l/2;g.L(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.jn(e.element,o3);g.L(e.element,d);(e=g.xd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.kh(e,"height",f+"px")}}}}};
g.h.yF=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())m2(this,this.u.impressionUrls),(a=g.zB())&&this.u.visualElement&&g.rB(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");m2(this,c.impressionUrls);(b=g.zB())&&g.rB(b,c.visualElement);this.player.P().xb&&this.player.ma("endscreenelementshown",a)}};
g.h.zF=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.hn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.hn(b,"ytp-ce-shown");this.player.P().xb&&this.player.ma("endscreenelementhidden",a)}};
g.h.DM=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.jn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Vy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.fn(c,"ytp-ce-element");){g.fn(c,"subscribe-label")&&n2(this,a);if(g.fn(c,"ytp-ce-channel-subscribe"))return;c=g.Td(c)}if(!c||g.fn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.ds(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.HN?(n2(this,a),this.oA(),this.player.pauseVideo(),c=g.yc(j2(this,a.targetUrl)),c=g.wc(c),g.WN(c,void 0,a.Gb)):(c=this.player.getVideoData().dc,
c=(0,g.x)(this.zN,this,c,j2(this,a.targetUrl),a.Gb),c=(0,g.x)(this.oA,this,c),n2(this,a,c))}}};
g.h.zN=function(a,b,c){var d=g.$o(b);a&&d&&(d.v||d.list)?g.JU(this.player.app,d.v,c,d.list,!1,void 0):g.VN(b,c)};
g.h.Vq=function(a,b){g.fn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.L(a.element,"ytp-ce-element-hover"):this.player.P().o?(new g.J(function(){g.L(a.element,"ytp-ce-element-hover")},200)).start():g.L(a.element,"ytp-ce-element-hover"),m2(this,b.BE),l2(this,b.id,!0))};
g.h.ds=function(a,b){g.hn(a.element,"ytp-ce-element-hover");g.hn(a.element,"ytp-ce-force-expand");l2(this,b.id,!1)};
g.h.oA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var n3=[346,426,470,506,570,640,853,1280,1920],o3="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),jpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Joa={qP:"current",MQ:"new"};var Koa={CLOSE:"close",PQ:"openUrl",lC:"subscribe"},Loa={kP:"click",CLOSE:"close",bQ:"hidden",nR:"rollOut",oR:"rollOver",rR:"shown"};var gpa={NO:"anchored",GB:"branding",CHANNEL:"channel",pP:"cta",dQ:"highlightText",vQ:"label",PLAYLIST:"playlist",ZQ:"popup",vR:"speech",lC:"subscribe",FR:"title",VIDEO:"video",SR:"website"},fpa={GB:"branding",bP:"card",wP:"drawer",cQ:"highlight",CQ:"marker",fR:"promotion",TEXT:"text",UR:"widget"};z2.prototype.u=function(a,b){var c=g.ae(b.target,"label");c&&g.M(c,"iv-card-poll-choice-focused",a)};
z2.prototype.w=function(a,b){var c=g.ae(b.target,null,"iv-card-poll",void 0);if(c)if(a.Lh)g.zd("iv-card-sign-in-button",c).click();else{var d=parseInt(voa(b.target),10);if(null==a.je)a.choices[d].count++,a.je=d;else if(a.je!=d){var e=a.choices[a.je];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.je=d}else e=a.choices[a.je],e.count=Math.max(e.count-1,0),a.je=null;B2(a,c);g.xp(this.o.videoData.Id,{Gd:{action_poll_vote:1},vb:{poll_id:a.id,index:d,session_token:a.lO}});y2(this.o.logger,a.uc.click,
void 0,5);(c=g.zB())&&a.Jd&&g.sB(c,a.Jd)}};g.r(J2,g.A);g.h=J2.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.qE(a,b,{id:c});g.B(this,a);a.namespace="annotations_module";d&&O1(a).subscribe("onEnter",d,this);e&&O1(a).subscribe("onExit",e,this);g.xL(this.context.ca,[a])};
g.h.Nk=function(){this.context.u.subscribe("resize",this.Il,this)};
g.h.Vi=function(a,b,c,d,e,f){this.context.o.ha(a,"click",g.Oa(this.Nm,b,c,d,e||[],f||0),this);this.context.o.ha(a,"touchstart",g.Oa(function(){this.Bt=!1}),this);
this.context.o.ha(a,"touchmove",g.Oa(function(){this.Bt=!0}),this)};
g.h.Nm=function(a,b,c,d,e,f){if(this.Bt)return!1;f&&(f.stopPropagation(),f.preventDefault());Uoa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Qd(this.o)};
g.h.Il=function(){};g.r(O2,J2);g.h=O2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.w.length)(a=this.A.getRootNode())?(a=g.Eh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Il=function(){var a=this.isAvailable();g.Fh(this.o,a);g.M(this.context.ca.getRootNode(),"ytp-iv-drawer-enabled",a);P1(this.A)};
g.h.destroy=function(){var a=g.pL(g.dL(this.A));a&&a.Uq(!1,void 0);this.A.getRootNode().removeChild(this.D);g.Bo(this.V);g.gr(this.aa);this.ba&&this.ba.dispose();this.G&&this.G.dispose();J2.prototype.destroy.call(this)};
g.h.VF=function(a){this.X.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.pA=function(a){if(!g.fn(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.zB(),c=this.u?this.u.card.Uc:this.J;b&&c&&R1(b,[c]);this.u=a;S2(this)}if(b="none"!=this.o.style.display)2==this.context.ca.getPresentingPlayerType()?b=1==this.context.ca.getAdState():(b=this.context.ca.getPlayerState(),c=0==b&&0===this.context.ca.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.pL(g.dL(this.A)))&&c.Uq(!0,
b));this.ga.isActive()||((!this.C||!this.X.isActive()&&this.da)&&U2(this,a),this.ga.start(910+a.card.teaserDurationMs))}};
g.h.rN=function(a){this.C||(this.u=a,S2(this),U2(this,a),M2(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.SC=function(){if(this.C){y2(this.context.logger,V2(this).uc.close);var a=g.zB();a&&this.U&&g.sB(a,this.U);N2(this)}};
g.h.gD=function(){g.M(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.aF=function(){var a=g.zB(),b=V2(this);b=b?b.Uc:this.J;a&&b&&Q1(a,[b])};
g.h.ZE=function(){var a=g.zB(),b=V2(this);b=b?b.Uc:this.J;a&&b&&R1(a,[b])};
g.h.dF=function(){var a=V2(this);y2(this.context.logger,a.uc.KA);var b=g.zB();b&&a&&Q1(b,[a.Ed,a.Uc])};
g.h.cF=function(){var a=g.zB(),b=V2(this);a&&b&&R1(a,[b.Ed])};
g.h.bF=function(a){var b=V2(this),c=g.zB();this.u?a?(a=this.context.logger,y2(a,b.uc.lo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Ed&&g.sB(c,b.Ed)):(a=this.context.logger,y2(a,b.uc.lo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Uc&&g.sB(c,b.Uc)):(a=this.context.logger,y2(a,b.uc.lo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.sB(c,this.J))};g.r(W2,J2);W2.prototype.Nk=function(){J2.prototype.Nk.call(this);bpa(this)};
W2.prototype.show=function(){J2.prototype.show.call(this);var a=g.zB(),b=this.annotation.data;a&&b&&(b=b.session_data)&&Q1(a,[g.dB(b.itct)])};
W2.prototype.hide=function(){J2.prototype.hide.call(this);var a=g.zB(),b=this.annotation.data;a&&b&&(b=b.session_data)&&R1(a,[g.dB(b.itct)])};g.r(X2,W2);g.h=X2.prototype;g.h.AN=function(a,b,c,d){this.w.stop();if(!this.B){var e=g.Eh(a);this.u||(g.Ch(a,e.width),g.Ch(b,e.width));g.kh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.kh(c,"right","1px");this.B=!0;g.Fh(a,!0);this.C=new g.J(function(){g.L(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.zE=function(a,b){g.hn(this.o,"iv-branding-active");this.D=new g.J((0,g.x)(function(){g.Fh(a,!1);this.u||g.Ch(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){W2.prototype.show.call(this);if(!this.G){g.L(this.o,"iv-branding");var a=this.annotation.data;this.A=g.Kd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Fh(this.A,!1);var b=g.Kd("DIV","branding-img-container",this.A);this.o.appendChild(b);(b=w2(this.annotation))&&this.Vi(this.A,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Kd("DIV","iv-branding-context-name");
g.Vd(c,a.channel_name);var d=g.Kd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.AR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ca),this.u.o(d);b=g.Kd("DIV","iv-branding-context-subscribe-caret");c=g.Kd("DIV","branding-context-container-inner",b,c,d);g.Fh(c,!1);d=g.Kd("DIV","branding-context-container-outer",c);g.kh(d,"right",
a.image_width+"px");this.o.appendChild(d);this.w=new g.J(g.Oa(this.zE,c,d),500,this);g.B(this,this.w);this.context.o.ha(this.o,"mouseover",(0,g.x)(this.AN,this,c,d,b,a.image_height));this.context.o.ha(this.o,"mouseout",(0,g.x)(this.w.start,this.w,void 0))}this.G=!0}g.Fh(this.o,!0);this.isActive=!0;if(this.A){a=this.A;var e=void 0===e?0:e;b=g.xh(a);c=g.Eh(a);b=(new g.hh(b.x,b.y,c.width,c.height)).width;g.sh(a,b);e=new a2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,woa);g.B(this,e);this.context.A.ha(e,
"begin",g.Oa(g.Fh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(W2.prototype.hide.call(this),g.Fh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);W2.prototype.destroy.call(this)};g.r(Y2,W2);g.h=Y2.prototype;g.h.show=function(){this.isActive||(W2.prototype.show.call(this),this.K||(cpa(this),this.K=!0),g.Fh(this.o,!0),g.qf(function(){g.hn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,a3(this),$2(this),b3(this,this.G))};
g.h.hide=function(){this.isActive&&(g.L(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Nm=function(a,b,c,d,e,f){return this.C?!1:W2.prototype.Nm.call(this,a,b,c,d,e,f)};
g.h.Zp=function(a,b){b.stopPropagation();$2(this);b3(this,a);this.u.focus()};
g.h.dE=function(a){this.J=!0;this.Zp(500,a)};
g.h.cE=function(){this.J=!1;Z2(this)};
g.h.VD=function(a){a.stopPropagation();this.hide()};
g.h.WD=function(a){a.stopPropagation();a3(this);this.C=!0;g.L(this.o,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();W2.prototype.destroy.call(this)};g.r(c3,g.VQ);g.h=c3.prototype;g.h.Ac=function(a,b){if(!e3(this.player.P().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.o0(b);c&&i3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(T2(this.o,b),P1(this.player)),!0}return null};
g.h.getOptions=function(){return e3(this.player.P().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.In=function(){if(this.w){var a=g.jL(this.player).getVideoContentRect(!0);g.Dh(this.w.element,a.width,a.height);g.sh(this.w.element,a.left,a.top)}if(this.o){var b=g.sL(this.player);a=this.o;b=b.width;g.M(a.D,"iv-drawer-small",426>=b);g.M(a.D,"iv-drawer-big",1280<=b)}};
g.h.bL=function(a){this.hc(a.state);g.X(a.state,2)&&(this.hk()&&this.ix()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Uq(!1))};
g.h.load=function(){g.VQ.prototype.load.call(this);this.hc(g.iL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.QJ,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Po()&&(c=j3(this,c));c={format:"XML",cd:c,onError:d,Gd:{}};a.isPharma&&(c.Gd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.P().D.get(b))&&k3(c,b);b=b&&(b.Nl||b.Ml);if(!a.Bl||b)a.Id?f3(this,a.Id,c):(this.A=(0,g.x)(this.wF,this,c),this.player.addEventListener("videodatachange",this.A));g.BL(this.player,this.w.element,4);this.In();(b=a.Ia&&a.Ia.cards&&a.Ia.cards.cardCollectionRenderer||null)&&hpa(this,b);(b=uoa(a))&&b.featuredChannel&&ipa(this,b.featuredChannel,b.annotationId||"branding",
a.videoId||null,a.eventId||null)};
g.h.hc=function(a){a=!a.isCued()&&!g.X(a,1024);g.zu(this.u,a);g.zu(this.w,a)};
g.h.wF=function(a){var b=this.player.getVideoData();b.Id&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),f3(this,b.Id,a))};
g.h.unload=function(){g.oS(this.player.app,"annotations_module",void 0);g.Ib(this.D,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,P1(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.D={};this.u.hide();g.VQ.prototype.unload.call(this);g.yu(this.w);this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.h.QJ=function(a,b,c){this.C=null;!h3(this,b,a)&&(a=g.np(c)&&c.responseXML?c.responseXML:null)&&(i3(this,a),g.L(this.player.getRootNode(),"iv-module-loaded"))};
g.h.wz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?epa(this):this.load())};
g.h.hk=function(){return!!this.o&&this.o.isAvailable()};
g.h.ix=function(){this.hk();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.hk();this.o&&(a?c?M2(this.o,c,b):M2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):N2(this.o))};
g.h.Uq=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Z=function(){this.player.P().D.unsubscribe("vast_info_card_add",this.wz,this);g.hn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.K,b=0,c=a.length;b<c;b++)g.Qo(a[b]);this.K.length=0;g.VQ.prototype.Z.call(this)};g.kR.annotations_module=c3;g.kR.creatorendscreen=e2;})(_yt_player);
